### ISSUE TITLE
  There are no commands defined in the "model-stats" namespace.  

### ISSUE THREAD

**Issue by Zouhairrrr** [JhumanJ/laravel-model-stats#4]
hey guys once i try to php artisan model-stats:install in my terminal, i get a message telling me that :
  There are no commands defined in the "model-stats" namespace.

**Comment by JhumanJ** [comment]
Hey, can you please give more context? What vesions of Laravel, package etc are you using? 
It seems like the package isn't properly installed.

**Comment by Zouhairrrr** [comment]
Hi i'm sorry i just notice that i didnt put the considered information for my issue so here it goes 
 - Laravel Installer 4.2.6
 - PHP 8.0.5 (cli) Copyright (c) The PHP Group Zend Engine v4.0.5
 - Composer version 2.1.1 
  something went wrong with my installation but now it works fine after i tried from scratch thanks for ur help so far
